services:
  mysql:
    image: mysql:8.0
    container_name: taskly_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - taskly_network

  backend:
    build: ./back
    container_name: taskly_backend
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_PORT: 3306
      JWT_SECRET: ${JWT_SECRET}
      TOKEN_EXPIRATION: ${TOKEN_EXPIRATION}
      PORT: ${PORT}
    ports:
      - "3000:3000"
    networks:
      - taskly_network

networks:
  taskly_network:
    driver: bridge

volumes:
  mysql_data:
