services:
  mysql:
    image: mysql:8.0
    container_name: taskly_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3000:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - taskly_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./back
    container_name: taskly_backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PORT: ${PORT}
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_DATABASE: ${MYSQL_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      TOKEN_EXPIRATION: ${TOKEN_EXPIRATION}
      API_KEY: ${API_KEY}
    ports:
      - "4000:${PORT}"
    networks:
      - taskly_network

  frontend:
    build: ./front
    container_name: taskly_frontend
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "5000:3000"
    networks:
      - taskly_network

networks:
  taskly_network:
    driver: bridge

volumes:
  mysql_data: